name: Build, Push and Trigger Humanitec Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: checkout code
      - uses: score-spec/setup-score@v2
        name: setup score
        with:
          file: score-humanitec
          version: '0.9.1'
      - name: Build and Push to Humanitec
        uses: humanitec/build-push-to-humanitec@v1
        id: push
        with:
          humanitec-token: ${{ secrets.HUMANITEC_TOKEN }}
          organization: ${{ secrets.HUMANITEC_ORG }}
          tag: ${{ github.run_number }}
          additional-docker-arguments: --build-arg VERSION=${{ github.run_number }}
      - name: Create Delta using Score
        run: |
          echo "DELTA=$(score-humanitec delta \
            --app list-env-vars-app \
            --org ${{ secrets.HUMANITEC_ORG }} \
            --token "${{ secrets.HUMANITEC_TOKEN }}" \
            --env "development" \
            --property "containers.list-env-vars.image=${{ steps.push.outputs.image }}" \
            | jq -r .id)" >> $GITHUB_ENV
      - name: print delta and build number
        run: echo $DELTA ${{ github.run_number }} 
      - name: echo commit msg
        run: |
          echo ${{ github.event.head_commit.message }}
      - name: trigger Humanitec pipeline
        run: |
          curl --location 'https://api.humanitec.io/orgs/${{ secrets.HUMANITEC_ORG }}/apps/list-env-vars-app/pipelines/${{ vars.HUM_PIPELINE_ID }}/runs' \
          --header 'Authorization: Bearer ${{ secrets.HUMANITEC_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data '{
                    "inputs":{
                      "delta_id":"'${DELTA}'",
                      "build":"${{ github.run_number }}",
                      "commit":"${{ github.event.head_commit.message }}"
                    }
                  }'
      
